name: Linux Build and Test
on: [push]
jobs:
  gcc:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: unix
    strategy:
      matrix:
        symbols:
          - "no"
          - "mem"
    steps:
      - name: Setup Environment
        run: |
          sudo apt-get install tcl8.6-dev libx11-dev xvfb
          mkdir "$HOME/install dir"
          echo "TEST_INSTALL_DIR=$HOME/install dir" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure (symbols=${{ matrix.symbols }})
        run: |
          ./configure ${CFGOPT} "--prefix=$TEST_INSTALL_DIR"
        env:
          CFGOPT: --enable-symbols=${{ matrix.symbols }}
      - name: Report Log on Configure Failure
        if: ${{ failure() }}
        run: cat config.log
      - name: Build
        run: make binaries libraries
      - name: Build Test Harness
        run: make tktest
      - name: Run Tests
        run: |
          xvfb-run --auto-servernum make test-classic | tee out-classic.txt
          xvfb-run --auto-servernum make test-ttk | tee out-ttk.txt
          cat out-classic.txt out-ttk.txt | grep -q "Failed	0"
        env:
          ERROR_ON_FAILURES: 1
      - name: Test-Drive Installation
        run: make install
      - name: Create Distribution Package
        run: make dist
      - name: Convert Documentation to HTML
        # Needs a Tcl source checkout
        if: false
        run: make html-tk
